### PR TITLE
Add posibility to test source code from GIT repo

### PR DESCRIPTION
**Pull request by frenzymadness**
As requested in https://github.com/frenzymadness/fedora-python-tox/issues/8 I've added a possibility to test source code automatically cloned from provided GIT URL.

Because it is complicated (impossible?) to run more than one command as an entry point, I decided to add a simple script which can handle environment variable and clone project from provided URL.

@fivaldi what do you think about it? @hroncok could you please review?

### CODE REVIEW

**Comment by fivaldi** [comment]
For some reason it gives me just:
`ERROR: toxini file 'tox.ini' not found
`

**Comment by frenzymadness** [comment]
@fivaldi Provide a command you are trying to execute, please.

**Comment by fivaldi** [comment]
@frenzymadness 
`docker run --rm -it -e GIT_URL=https://pagure.io/forks/fivaldi/modulemd.git frenzymadness/fedora-python-tox`

**Comment by fivaldi** [comment]
@frenzymadness But the file is (_should be_) in the master branch of the repo, see:
https://pagure.io/fork/fivaldi/modulemd/tree/master

**Comment by frenzymadness** [comment]
@fivaldi Did you build your own image from source from this PR before the test? I did and tests with your repository executed by command mentioned by you works.

```
# Built
$ docker build -t frenzymadness/fedora-python-tox .
....
# Run
$ docker run --rm -it -e GIT_URL=https://pagure.io/forks/fivaldi/modulemd.git frenzymadness/fedora-python-tox
Cloning into 'temp_project_dir'...
remote: Counting objects: 861, done.
remote: Compressing objects: 100% (696/696), done.
remote: Total 861 (delta 544), reused 254 (delta 134)
Receiving objects: 100% (861/861), 161.39 KiB | 354.00 KiB/s, done.
Resolving deltas: 100% (544/544), done.
py27 create: /temp_project_dir/.tox/py27
py27 installdeps: pytest
py27 develop-inst: /temp_project_dir
... and the long output from your tests ....
```

Obviously, you don't have to build it for you once this PR will be merged and the new image appears in Docker hub.

**Comment by hroncok** [comment]
Might be selinux thing as well, juts got bit by this a minute ago.

**Comment by frenzymadness** [comment]
Rebased, rebuilt, tested and works.

**Comment by fivaldi** [comment]
@frenzymadness Just a question: Why is it needed to build user's own docker image? Is there supposed to be anything specific in the Dockerfile for building local images?

I would prefer running an already existing image. The difference in size between the uncompressed images is 1.28 GB (original) versus 1.31 (built). Travis CI would just push an updated image after pushing to the master of this repo. Does it makes sense or did I missed something?

**Comment by hroncok** [comment]
> Why is it needed to build user's own docker image?

Because the prebuilt images are from the master branch and this PR is not yet merged.

**Comment by fivaldi** [comment]
@hroncok Sorry, of course. Thanks! 
@frenzymadness Feel free to merge it...

**Comment by frenzymadness** [comment]
I moved example project to its own repository so we can now test both options - source code mounted from local folder to Docker container as well as source code cloned from Git URL into Docker container.

Travis now tests both cases.

What do you think @hroncok and @fivaldi?

**Comment by hroncok** [comment]
Is there any any reason to have it as a submodule at all?

**Comment by frenzymadness** [comment]
Yes, I want to ship it in a simple way with the main project for users to be able to simply run some tests after Dockerfile modifications or when they will be considering our Docker image as a base for their tests. It also adds a possibility to test "local source code" in Travis and remote repository as well with only one codebase.

Moreover, if you don't want to, you don't have to use it.

I don't see anything against this idea.

**Comment by hroncok** [comment]
Ok. I've just asked.

**Comment by fivaldi** [comment]
I like the idea for both use cases: Testing from sources as well as git repo.

Give this PR a go! 💪

**Pull request merged**
